title: Xen Crypto Documentation
description: XEN is a cryptocurrency for the masses. It is designed and built to deliver on the First Principles of Crypto.

author:
  name: Fair Crypto Foundation
  url: https://faircrypto.org

plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/XEN-crypto" }
    - { platform: twitter, user_url: "https://twitter.com/XEN_Crypto" }
    - { platform: telegram, user_url: "https://t.me/XENCryptoTalk" }
    - { platform: youtube, user_url: "https://m.youtube.com/channel/UCiw5nyHHt9BPHvoRbcGNehA/playlists" }
show_excerpts: false
